# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semirest', '0002_auto_20161214_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
