# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20161213_1854'),
        ('courselist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='registered_students', to='loginreg.User'),
        ),
    ]
